package dev.frost.frostcore.teams;

public enum TeamError {
    TEAM_ALREADY_EXISTS,
    TEAM_NOT_FOUND,

    PLAYER_ALREADY_IN_TEAM,
    PLAYER_NOT_IN_TEAM,

    TEAM_NAME_TOO_SHORT,
    TEAM_NAME_TOO_LONG,
    TEAM_NAME_BANNED,

    TEAM_FULL,

    MAX_ADMINS_REACHED,
    MAX_OWNERS_REACHED,
    NOT_OWNER,
    NOT_ADMIN,

    WARPS_DISABLED,
    MAX_WARPS_REACHED,
    WARP_DOES_NOT_EXIST,
    WARP_ALREADY_EXISTS,

    ALLIES_DISABLED,
    ENEMIES_DISABLED,
    MAX_ALLIES_REACHED,
    MAX_ENEMIES_REACHED,
    ALREADY_ALLY,
    ALREADY_ENEMY,
    NOT_ALLY,
    NOT_ENEMY,
    CANNOT_TARGET_SELF,

    HOME_DISABLED,

    ONLY_OWNER,
    ONLY_ADMIN,

    CANNOT_LEAVE_AS_OWNER,
    CANNOT_KICK_HIGHER_ROLE,
    ALREADY_HIGHEST_RANK,
    ALREADY_LOWEST_RANK,
    CANNOT_DEMOTE_LAST_OWNER
}
